### ISSUE TITLE
Provide UI view for Jobs

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#416]
**Desired behaviour:**

- Jobs listed in the UI should eventually be able to grouped by a Session instances. However for the first implementation, only Jobs should be shown in the UI, Tasks do not need to be shown.
- Filtering by several fields (status, job type, creator (My jobs, Project members, Others/Anonymous)

**Designs:**
https://www.figma.com/file/ARJX8ZMKvBAgW0gp3VYE0X/Executable-document-workflow?node-id=60539%3A27154

**Todos:**
- [x] Finalize simplified mockup for initial deliverable version @alex-ketch 
- [x] Define colours and graphic assets to be used for elements @alex-ketch 
- [x] Create Jobs listing view @simonwinter
- [x] Create Job detail view @simonwinter

**Comment by alex-ketch** [comment]
Not sure why this got re-opened 🤔
This issue was closed by #448, and any carryover work is tracked by https://github.com/stencila/hub/issues/453
