### ISSUE TITLE
Add ability to Clone (Fork) projects

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#423]
**Use case:**
Given an author who owns a Project with an executable article of theirs, the author can invite a contact person from a publishing journal to review their Project.
In this scenario the publisher wants to ensure that the Project will not be deleted, so they clone/fork the Project to their own Account before snapshotting and publishing it.

**Tasks:**

- [ ] Add cloning functionality to the Hub
- [ ] Add a `Clone` button to the Project overview view
- [ ] _Stretch goal:_ Add ability to initiate a Forking feature via a URL query to support a `Clone this article` button in https://github.com/stencila/designa/issues/44

**Considerations:**

- We'll use "clone" as the chosen vocabulary for creating copies of projects into other accounts
- Project should be able to be Forked from the latest Project state
- Fork should copy over a reference to the original Project's snapshots (Investigate: What happens to Snapshots when a Project is deleted)

---

**Alternative solution:**
Ability to transfer ownership of Projects
Manually clone a project for publisher from admin interfaces

---

**Prior conversations:**
- https://github.com/stencila/hub/issues/184#issuecomment-470845189
