### ISSUE TITLE
When serving Executable Documents, add toolbar to articles

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#442]
This issue is about the work needed in the Hub to integrate the component from https://github.com/stencila/designa/issues/44

**Todo:**

- [ ] Create a template file with the necessary toolbar markup
- [ ] Write and connect JS logic for connecting to the execution instance, and adding execution handlers to Code elements. This will likely require a bit of front-end build tooling setup in the Hub.
- [ ] Add component to markup when serving executable articles
  - [ ] _Stretch goal:_ Only add toolbar if article contains `CodeChunk` or `CodeFragment` components

**Comment by alex-ketch** [comment]
Closed by https://github.com/stencila/hub/pull/589
